# ... existing code ...
# Update the function call to include the required arguments
weather_df = create_weather_dataframe(latitude, longitude, start_date, end_date, location)
# ... existing code ... 